/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JeunesseProfileCoreSmartMobileRegisterDeviceTokenRequestModel struct {
	MainFK          int32  `json:"mainFK"`
	DeviceType      string `json:"deviceType"`
	DeviceToken     string `json:"deviceToken"`
	ApplicationName string `json:"applicationName"`
}
