/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

import (
	"time"
)

type JeunesseBackDataPocoAwardsAward struct {
	AwardPk      int32     `json:"awardPk"`
	AwardTypeFk  int32     `json:"awardTypeFk"`
	AwardRankFk  int32     `json:"awardRankFk,omitempty"`
	AwardForQty  int32     `json:"awardForQty,omitempty"`
	MainFk       int32     `json:"mainFk"`
	DateReceived time.Time `json:"dateReceived"`
	ReceivedBy   int32     `json:"receivedBy"`
	Location     string    `json:"location,omitempty"`
}
