/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreWalletModelsSignupTokensSignupTokenViewModel struct {
	SignupTokens []JeunesseProfileCoreWalletModelsSignupTokensGetSignupTokensReportResult `json:"signupTokens,omitempty"`
	CurrentPage  int32                                                                    `json:"currentPage,omitempty"`
	TotalCount   int32                                                                    `json:"totalCount,omitempty"`
}
