/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JeunesseProfileCoreWalletModelsEftEftFormModel struct {
	NxPayAccountPK     int32  `json:"nxPayAccountPK,omitempty"`
	Success            bool   `json:"success,omitempty"`
	AccountDescription string `json:"accountDescription,omitempty"`
	Personal           string `json:"personal,omitempty"`
	BankAddress2       string `json:"bankAddress2,omitempty"`
	BankCity           string `json:"bankCity,omitempty"`
	BankKey            string `json:"bankKey,omitempty"`
	BankState          string `json:"bankState,omitempty"`
	BankZip            string `json:"bankZip,omitempty"`
	HoldingBranchCode  string `json:"holdingBranchCode,omitempty"`
	CheckDigits        string `json:"checkDigits,omitempty"`
	FreeForm1          string `json:"freeForm1,omitempty"`
	Active             bool   `json:"active,omitempty"`
	AccountCurrency    string `json:"accountCurrency,omitempty"`
	NameAccount        string `json:"nameAccount,omitempty"`
	AccountNumber      string `json:"accountNumber,omitempty"`
	AccountType        int32  `json:"accountType,omitempty"`
	BankCode           string `json:"bankCode,omitempty"`
	BankName           string `json:"bankName,omitempty"`
	BankCountry        string `json:"bankCountry,omitempty"`
	BankSort           string `json:"bankSort,omitempty"`
	BankAddress1       string `json:"bankAddress1,omitempty"`
	BranchCode         string `json:"branchCode,omitempty"`
	Iban               string `json:"iban,omitempty"`
	RoutingNumber      string `json:"routingNumber,omitempty"`
	SwiftBic           string `json:"swift_bic,omitempty"`
}
