/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JeunesseProfileCoreSponsorshipModelsSponsorshipReportQueryModel struct {
	MainSiteUrl         string `json:"mainSiteUrl,omitempty"`
	SiteURL             string `json:"siteURL,omitempty"`
	FName               string `json:"fName,omitempty"`
	LName               string `json:"lName,omitempty"`
	DisplayName         string `json:"displayName,omitempty"`
	IsCountedByPlatinum bool   `json:"isCountedByPlatinum,omitempty"`
	Statuses            string `json:"statuses,omitempty"`
	HighestRanks        string `json:"highestRanks,omitempty"`
	SearchMainPK        int32  `json:"searchMainPK,omitempty"`
}
