/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreDashboardsModelsSmartMobileProductCountApiResponseModel struct {
	Year            int32                                                        `json:"year,omitempty"`
	Month           int32                                                        `json:"month,omitempty"`
	MonthYear       int32                                                        `json:"monthYear,omitempty"`
	ProductID       int32                                                        `json:"productID,omitempty"`
	Name            string                                                       `json:"name,omitempty"`
	TotalSales      float64                                                      `json:"totalSales,omitempty"`
	TotalSalesValue *JeunesseProfileCoreDashboardsModelsSmartMobileCurrencyModel `json:"totalSalesValue,omitempty"`
	TotalSalesCount int32                                                        `json:"totalSalesCount,omitempty"`
	Percent         int32                                                        `json:"percent,omitempty"`
	CurrencySymbol  string                                                       `json:"currencySymbol,omitempty"`
	CurrencyFormat  string                                                       `json:"currencyFormat,omitempty"`
	CurrencyCode    string                                                       `json:"currencyCode,omitempty"`
}
