/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreDashboardsModelsBpSpSnapshotModel struct {
	Category   string  `json:"category,omitempty"`
	Bp         float64 `json:"bp,omitempty"`
	Sp         float64 `json:"sp,omitempty"`
	TlGroupBP  float64 `json:"tlGroupBP,omitempty"`
	TlGroupSP  float64 `json:"tlGroupSP,omitempty"`
	DGroupBP   float64 `json:"dGroupBP,omitempty"`
	DGroupSP   float64 `json:"dGroupSP,omitempty"`
	SdGroupBP  float64 `json:"sdGroupBP,omitempty"`
	SdGroupSP  float64 `json:"sdGroupSP,omitempty"`
	NdGroupBP  float64 `json:"ndGroupBP,omitempty"`
	NdGroupSP  float64 `json:"ndGroupSP,omitempty"`
	SpRequired float64 `json:"spRequired,omitempty"`
	SpNeeded   float64 `json:"spNeeded,omitempty"`
	CurrRank   string  `json:"currRank,omitempty"`
}
