/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

import (
	"time"
)

type JeunesseProfileCoreDashboardsModelsPersonalInfoModel struct {
	SiteURL                        string    `json:"siteURL,omitempty"`
	MostRecentMonthSD              time.Time `json:"mostRecentMonthSD,omitempty"`
	MostRecentMonthED              time.Time `json:"mostRecentMonthED,omitempty"`
	CurrentRank                    int32     `json:"currentRank,omitempty"`
	CurrentRankName                string    `json:"currentRankName,omitempty"`
	NextRank                       int32     `json:"nextRank,omitempty"`
	NextRankName                   string    `json:"nextRankName,omitempty"`
	AccumulatingSP                 float64   `json:"accumulatingSP,omitempty"`
	RequireSPForNextRank           float64   `json:"requireSPForNextRank,omitempty"`
	NeededSPForNextRank            float64   `json:"neededSPForNextRank,omitempty"`
	LegsSM                         int32     `json:"legsSM,omitempty"`
	RequiredLegsSM                 int32     `json:"requiredLegsSM,omitempty"`
	LegsTL                         int32     `json:"legsTL,omitempty"`
	RequiredLegsTL                 int32     `json:"requiredLegsTL,omitempty"`
	LegsD                          int32     `json:"legsD,omitempty"`
	RequiredLegsD                  int32     `json:"requiredLegsD,omitempty"`
	RetailCustomerCount            int32     `json:"retailCustomerCount,omitempty"`
	RequiredRetailCustomerCount    int32     `json:"requiredRetailCustomerCount,omitempty"`
	MOrHigherCount                 int32     `json:"mOrHigherCount,omitempty"`
	RequiredMOrHigherCount         int32     `json:"requiredMOrHigherCount,omitempty"`
	StrMoreThanReqSPLegs           string    `json:"strMoreThanReqSPLegs,omitempty"`
	StrMoreThanReqMLegs            string    `json:"strMoreThanReqMLegs,omitempty"`
	RankAdvanceEligibleDisplayText string    `json:"rankAdvanceEligibleDisplayText,omitempty"`
	PaidAsRankName                 string    `json:"paidAsRankName,omitempty"`
	HighestAchievedRankName        string    `json:"highestAchievedRankName,omitempty"`
	HighestAchievedRankDate        time.Time `json:"highestAchievedRankDate,omitempty"`
	IsPaidAsQualified              bool      `json:"isPaidAsQualified,omitempty"`
	CurrentSP                      float64   `json:"currentSP,omitempty"`
	RequiredMonthlySP              float64   `json:"requiredMonthlySP,omitempty"`
	AutoshipCustomerCount          int32     `json:"autoshipCustomerCount,omitempty"`
	RequiredAutoshipCustomerCount  int32     `json:"requiredAutoshipCustomerCount,omitempty"`
}
