/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreWalletModelsUpdatePasswordFormModel struct {
	Email              string                                          `json:"email,omitempty"`
	Phone              string                                          `json:"phone,omitempty"`
	Password           string                                          `json:"password,omitempty"`
	UseAnswersFromMain bool                                            `json:"useAnswersFromMain,omitempty"`
	QuestionsAnswers   []JeunesseProfileCoreWalletModelsQuestionAnswer `json:"questionsAnswers,omitempty"`
	LiToken            string                                          `json:"liToken,omitempty"`
}
