/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreMemberModelsTwUnifiedTwUnifiedInfo struct {
	ContainerType     int32  `json:"containerType,omitempty"`
	ContainerNumber   string `json:"containerNumber,omitempty"`
	ContainerTypeCode string `json:"containerTypeCode,omitempty"`
	ContainerCode     string `json:"containerCode,omitempty"`
	IsCurrentOption   bool   `json:"isCurrentOption,omitempty"`
}
