/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type JeunesseProfileCoreWalletModelsSignupTokensSignupTokensQueryModel struct {
	MainId          int32     `json:"mainId,omitempty"`
	TokenName       string    `json:"tokenName,omitempty"`
	TokenStartDate  time.Time `json:"tokenStartDate,omitempty"`
	TokenEndDate    time.Time `json:"tokenEndDate,omitempty"`
	TokenStatus     string    `json:"tokenStatus"`
	UseMainOrdersFK int32     `json:"useMainOrdersFK,omitempty"`
	PageSize        int32     `json:"pageSize,omitempty"`
	PageNumber      int32     `json:"pageNumber,omitempty"`
	OrderBy         string    `json:"orderBy,omitempty"`
}
