/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JeunesseProfileCoreUsersModelsMainUserQueryModel struct {
	Search         string `json:"search,omitempty"`
	ExactSearch    bool   `json:"exactSearch,omitempty"`
	SiteUrl        string `json:"siteUrl,omitempty"`
	MainPK         int32  `json:"mainPK,omitempty"`
	Email          string `json:"email,omitempty"`
	FirstName      string `json:"firstName,omitempty"`
	LastName       string `json:"lastName,omitempty"`
	Company        string `json:"company,omitempty"`
	Phone          string `json:"phone,omitempty"`
	SponsorSiteUrl string `json:"sponsorSiteUrl,omitempty"`
	OrderNumber    int32  `json:"orderNumber,omitempty"`
	SkipCount      bool   `json:"skipCount,omitempty"`
	MainType       string `json:"mainType,omitempty"`
	OrderBy        string `json:"orderBy,omitempty"`
	Offset         int32  `json:"offset,omitempty"`
	Limit          int32  `json:"limit,omitempty"`
}
