/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreRepSiteModelsReplicateSiteViewModel struct {
	MainPk                       int32    `json:"mainPk,omitempty"`
	Name                         string   `json:"name,omitempty"`
	Phone                        string   `json:"phone,omitempty"`
	Email                        string   `json:"email,omitempty"`
	IsInventory                  bool     `json:"isInventory,omitempty"`
	ShowOption                   string   `json:"showOption,omitempty"`
	CinsayUrl                    string   `json:"cinsayUrl,omitempty"`
	ShowCinsay                   bool     `json:"showCinsay,omitempty"`
	JSocial                      bool     `json:"jSocial,omitempty"`
	Alias                        string   `json:"alias,omitempty"`
	CanShowPrefCust              bool     `json:"canShowPrefCust,omitempty"`
	CanShowJoinNowLink           bool     `json:"canShowJoinNowLink,omitempty"`
	GoogleAnalyticsUA            string   `json:"googleAnalyticsUA,omitempty"`
	IsWholesaleCustomer          bool     `json:"isWholesaleCustomer,omitempty"`
	CanAllowRetailCustomer       bool     `json:"canAllowRetailCustomer,omitempty"`
	CanAllowRetailSignup         bool     `json:"canAllowRetailSignup,omitempty"`
	FacebookPixelId              string   `json:"facebookPixelId,omitempty"`
	FacebookDomainKey            string   `json:"facebookDomainKey,omitempty"`
	IsCCAP                       bool     `json:"isCCAP,omitempty"`
	IsCorporate                  bool     `json:"isCorporate,omitempty"`
	Corporate                    bool     `json:"corporate,omitempty"`
	AvailableSamplesCountryCodes []string `json:"availableSamplesCountryCodes,omitempty"`
	MainReferrerFK               int32    `json:"mainReferrerFK,omitempty"`
	MainTypeFK                   int32    `json:"mainTypeFK,omitempty"`
	SponsorTypes                 []string `json:"sponsorTypes,omitempty"`
	Country                      string   `json:"country,omitempty"`
}
