/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreWalletModelsEftDocumentModel struct {
	SignupDocumentsPK int32  `json:"signupDocumentsPK,omitempty"`
	DocumentName      string `json:"documentName,omitempty"`
	Title             string `json:"title,omitempty"`
	UploadNotice      string `json:"uploadNotice,omitempty"`
	AllowedExtensions string `json:"allowedExtensions,omitempty"`
	UserDocumentsFK   int32  `json:"userDocumentsFK,omitempty"`
	FolderId          string `json:"folderId,omitempty"`
}
