/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type JeunesseProfileCoreWalletModelsFundRequestFundRequestModel struct {
	SequencePK      int32     `json:"sequencePK,omitempty"`
	RequestDate     time.Time `json:"requestDate,omitempty"`
	Amount          float64   `json:"amount,omitempty"`
	AmountFormatted string    `json:"amountFormatted,omitempty"`
	PayoutMethod    string    `json:"payoutMethod,omitempty"`
	CompleteDate    time.Time `json:"completeDate,omitempty"`
	Status          string    `json:"status,omitempty"`
	IsPaid          bool      `json:"isPaid,omitempty"`
}
