/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreWalletModelsCheckAttemptsResponse struct {
	Result        string `json:"result,omitempty"`
	Message       string `json:"message,omitempty"`
	QuestionPk    int32  `json:"questionPk,omitempty"`
	Question      string `json:"question,omitempty"`
	ResetAttempts int32  `json:"resetAttempts,omitempty"`
}
