/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JeunesseProfileCoreWalletModelsEftAccountCurrencyModel struct {
	CurrencyCode string `json:"currencyCode,omitempty"`
	CurrencyName string `json:"currencyName,omitempty"`
}
