/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

import (
	"time"
)

type JeunesseProfileCoreMemberMemberModel struct {
	SiteUrl          string                                                                   `json:"siteUrl"`
	SponsorUsername  string                                                                   `json:"sponsorUsername,omitempty"`
	FirstName        string                                                                   `json:"firstName"`
	MiddleName       string                                                                   `json:"middleName,omitempty"`
	CourtesyTitle    string                                                                   `json:"courtesyTitle,omitempty"`
	LastName         string                                                                   `json:"lastName"`
	Suffix           string                                                                   `json:"suffix,omitempty"`
	FirstName2       string                                                                   `json:"firstName2,omitempty"`
	LastName2        string                                                                   `json:"lastName2,omitempty"`
	Company          string                                                                   `json:"company,omitempty"`
	ScreenName       string                                                                   `json:"screenName,omitempty"`
	Payee            string                                                                   `json:"payee,omitempty"`
	Address1         string                                                                   `json:"address1,omitempty"`
	Address2         string                                                                   `json:"address2,omitempty"`
	Address3         string                                                                   `json:"address3,omitempty"`
	City             string                                                                   `json:"city,omitempty"`
	State            string                                                                   `json:"state,omitempty"`
	OtherState       string                                                                   `json:"otherState,omitempty"`
	PostalCode       string                                                                   `json:"postalCode,omitempty"`
	Country          string                                                                   `json:"country"`
	UseBilling       bool                                                                     `json:"useBilling,omitempty"`
	ShipFirstName    string                                                                   `json:"shipFirstName,omitempty"`
	ShipLastName     string                                                                   `json:"shipLastName,omitempty"`
	ShipAddress1     string                                                                   `json:"shipAddress1,omitempty"`
	ShipAddress2     string                                                                   `json:"shipAddress2,omitempty"`
	ShipAddress3     string                                                                   `json:"shipAddress3,omitempty"`
	ShipCity         string                                                                   `json:"shipCity,omitempty"`
	ShipState        string                                                                   `json:"shipState,omitempty"`
	ShipOtherState   string                                                                   `json:"shipOtherState,omitempty"`
	ShipPostalCode   string                                                                   `json:"shipPostalCode,omitempty"`
	ShipCountry      string                                                                   `json:"shipCountry,omitempty"`
	PhoneNumber      string                                                                   `json:"phoneNumber"`
	PhoneNumber2     string                                                                   `json:"phoneNumber2,omitempty"`
	Fax              string                                                                   `json:"fax,omitempty"`
	Email            string                                                                   `json:"email"`
	Password         string                                                                   `json:"password"`
	Ssn              string                                                                   `json:"ssn,omitempty"`
	IdType           int32                                                                    `json:"idType,omitempty"`
	Referrer         int32                                                                    `json:"referrer"`
	Area             string                                                                   `json:"area,omitempty"`
	DateOfBirth      string                                                                   `json:"dateOfBirth,omitempty"`
	CoAppName        string                                                                   `json:"coAppName,omitempty"`
	CoAppSsn         string                                                                   `json:"coAppSsn,omitempty"`
	IsCorporate      int32                                                                    `json:"isCorporate,omitempty"`
	MainTypeFK       int32                                                                    `json:"mainTypeFK"`
	Gender           string                                                                   `json:"gender,omitempty"`
	PersonalTaxID    string                                                                   `json:"personalTaxID,omitempty"`
	LanguageFK       int32                                                                    `json:"languageFK,omitempty"`
	AutoshipDate     time.Time                                                                `json:"autoshipDate,omitempty"`
	AnniversaryDate  time.Time                                                                `json:"anniversaryDate,omitempty"`
	CheckedW8BEN     bool                                                                     `json:"checkedW8BEN,omitempty"`
	CheckedW8BENDate time.Time                                                                `json:"checkedW8BENDate,omitempty"`
	RepSiteService   *JeunesseProfileCoreRepSiteRepSiteService                                `json:"repSiteService,omitempty"`
	SmsPhoneNumber   string                                                                   `json:"smsPhoneNumber,omitempty"`
	Culture          string                                                                   `json:"culture,omitempty"`
	WillReceiveSMS   bool                                                                     `json:"willReceiveSMS,omitempty"`
	MemberID         string                                                                   `json:"memberID,omitempty"`
	UserValidation   *JeunesseProfileCoreUsersModelsUserVerificationSignupUserValidationModel `json:"userValidation,omitempty"`
}
