/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JeunesseProfileCoreWalletModelsFundRequestInvoiceFundRequestInvoiceFormModel struct {
	MainId           int32  `json:"mainId,omitempty"`
	CheckRunId       int32  `json:"checkRunId,omitempty"`
	WithholdRecordId int32  `json:"withholdRecordId,omitempty"`
	IsValid          bool   `json:"isValid,omitempty"`
	InvalidReason    string `json:"invalidReason,omitempty"`
}
