/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type JeunesseProfileCoreWalletModelsAccountDetailsModel struct {
	FirstName   string    `json:"firstName,omitempty"`
	LastName    string    `json:"lastName,omitempty"`
	Company     string    `json:"company,omitempty"`
	Address1    string    `json:"address1,omitempty"`
	Address2    string    `json:"address2,omitempty"`
	City        string    `json:"city,omitempty"`
	State       string    `json:"state,omitempty"`
	StateName   string    `json:"stateName,omitempty"`
	Zip         string    `json:"zip,omitempty"`
	CountryName string    `json:"countryName,omitempty"`
	GmtOffSet   int32     `json:"gmtOffSet,omitempty"`
	TimeZone    string    `json:"timeZone,omitempty"`
	Email       string    `json:"email,omitempty"`
	Dob         time.Time `json:"dob,omitempty"`
	HomePhone   string    `json:"homePhone,omitempty"`
	WorkPhone   string    `json:"workPhone,omitempty"`
	Gender      string    `json:"gender,omitempty"`
}
