/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreDashboardsModelsGetCommissionsTotalApiResponseModel struct {
	CurrencySymbol       string                                                       `json:"currencySymbol,omitempty"`
	CurrencyFormat       string                                                       `json:"currencyFormat,omitempty"`
	CurrencyCode         string                                                       `json:"currencyCode,omitempty"`
	TotalCommisions      float64                                                      `json:"totalCommisions,omitempty"`
	TotalCommisionsValue *JeunesseProfileCoreDashboardsModelsSmartMobileCurrencyModel `json:"totalCommisionsValue,omitempty"`
}
