/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

import (
	"time"
)

type JeunesseProfileCoreUsersModelsSmartMobileContactModel struct {
	ContactID        int32                                                        `json:"contactID,omitempty"`
	ContactTypeID    int32                                                        `json:"contactTypeID,omitempty"`
	MainFK           int32                                                        `json:"mainFK,omitempty"`
	LeadFK           int32                                                        `json:"leadFK,omitempty"`
	FirstName        string                                                       `json:"firstName,omitempty"`
	LastName         string                                                       `json:"lastName,omitempty"`
	Phone1           string                                                       `json:"phone1,omitempty"`
	Phone2           string                                                       `json:"phone2,omitempty"`
	Email            string                                                       `json:"email,omitempty"`
	Address1         string                                                       `json:"address1,omitempty"`
	Address2         string                                                       `json:"address2,omitempty"`
	Address3         string                                                       `json:"address3,omitempty"`
	Country          string                                                       `json:"country,omitempty"`
	State            string                                                       `json:"state,omitempty"`
	City             string                                                       `json:"city,omitempty"`
	PostalCode       string                                                       `json:"postalCode,omitempty"`
	DateOfBirth      time.Time                                                    `json:"dateOfBirth,omitempty"`
	LastDateModified time.Time                                                    `json:"lastDateModified,omitempty"`
	DateCreated      time.Time                                                    `json:"dateCreated,omitempty"`
	TotalSalesValue  float64                                                      `json:"totalSalesValue,omitempty"`
	TotalSales       *JeunesseProfileCoreDashboardsModelsSmartMobileCurrencyModel `json:"totalSales,omitempty"`
	LastOrderDate    time.Time                                                    `json:"lastOrderDate,omitempty"`
	Tier             string                                                       `json:"tier,omitempty"`
}
