/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

import (
	"time"
)

type JeunesseProfileCoreMemberCustomerModel struct {
	MainPK           int32     `json:"mainPK,omitempty"`
	ReferrerMainFK   int32     `json:"referrerMainFK,omitempty"`
	FirstName        string    `json:"firstName,omitempty"`
	LastName         string    `json:"lastName,omitempty"`
	CultureName      string    `json:"cultureName,omitempty"`
	Email            string    `json:"email,omitempty"`
	Phone            string    `json:"phone,omitempty"`
	Address1         string    `json:"address1,omitempty"`
	Address2         string    `json:"address2,omitempty"`
	City             string    `json:"city,omitempty"`
	State            string    `json:"state,omitempty"`
	Zip              string    `json:"zip,omitempty"`
	Country          string    `json:"country,omitempty"`
	DateCreated      time.Time `json:"dateCreated,omitempty"`
	SiteURL          string    `json:"siteURL,omitempty"`
	TitleCourtesy    string    `json:"titleCourtesy,omitempty"`
	Dob              time.Time `json:"dob,omitempty"`
	Mi               string    `json:"mi,omitempty"`
	Suffix           string    `json:"suffix,omitempty"`
	WillReceiveSms   bool      `json:"willReceiveSms,omitempty"`
	WillReceiveEmail bool      `json:"willReceiveEmail,omitempty"`
	Secondphone      string    `json:"secondphone,omitempty"`
	Fax              string    `json:"fax,omitempty"`
}
