/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreMessagesModelsAlertsQueryModel struct {
	MainFK            int32   `json:"mainFK,omitempty"`
	DeviceCultureName string  `json:"deviceCultureName,omitempty"`
	AlertIDs          string  `json:"alertIDs,omitempty"`
	AlertPKs          []int32 `json:"alertPKs,omitempty"`
	IsRead            bool    `json:"isRead,omitempty"`
}
