/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreDashboardsModelsEventTicketsSnapshot struct {
	MainPK             int32   `json:"mainPK,omitempty"`
	FullName           string  `json:"fullName,omitempty"`
	MemberID           string  `json:"memberID,omitempty"`
	Username           string  `json:"username,omitempty"`
	RankPK             int32   `json:"rankPK,omitempty"`
	RankCode           string  `json:"rankCode,omitempty"`
	RankName           string  `json:"rankName,omitempty"`
	GroupTickets       int32   `json:"groupTickets,omitempty"`
	PersTickets        int32   `json:"persTickets,omitempty"`
	TeamTickets        int32   `json:"teamTickets,omitempty"`
	Rn                 int32   `json:"rn,omitempty"`
	TotalRegistrants   int32   `json:"totalRegistrants,omitempty"`
	TotalCheckIns      int32   `json:"totalCheckIns,omitempty"`
	TotalOrders        int32   `json:"totalOrders,omitempty"`
	TotalSales         float64 `json:"totalSales,omitempty"`
	TotalRefunded      float64 `json:"totalRefunded,omitempty"`
	TotalPurchasers    int32   `json:"totalPurchasers,omitempty"`
	GroupTicketsWOPers int32   `json:"groupTicketsWOPers,omitempty"`
}
