/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type JeunesseProfileCoreWalletModelsPhotoIdUpdatePhotoIdFormModel struct {
	MainId   int32     `json:"mainId,omitempty"`
	FolderId string    `json:"folderId,omitempty"`
	Type_    string    `json:"type,omitempty"`
	Number   string    `json:"number,omitempty"`
	ExpDate  time.Time `json:"expDate,omitempty"`
	NoExpiry bool      `json:"noExpiry,omitempty"`
	Country  string    `json:"country,omitempty"`
}
