/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreMessagesModelsSmNewsQueryModel struct {
	Username          string   `json:"username,omitempty"`
	LastArticleFK     int32    `json:"lastArticleFK,omitempty"`
	Length            int32    `json:"length,omitempty"`
	Categories        string   `json:"categories,omitempty"`
	CategoryKeys      []string `json:"categoryKeys,omitempty"`
	MainFK            int32    `json:"mainFK,omitempty"`
	DeviceCultureName string   `json:"deviceCultureName,omitempty"`
	Title             string   `json:"title,omitempty"`
}
