/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JeunesseProfileCoreMessagesModelsMailUpdateQueryModel struct {
	MainFK     int32   `json:"mainFK,omitempty"`
	MessageIDs string  `json:"messageIDs,omitempty"`
	MessagePKs []int32 `json:"messagePKs,omitempty"`
	IsRead     bool    `json:"isRead,omitempty"`
	IsDeleted  bool    `json:"isDeleted,omitempty"`
	IsFavorite bool    `json:"isFavorite,omitempty"`
}
