/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type JeunesseProfileCoreMemberModelsSetMemberPriceListFormModel struct {
	MainFK          int32     `json:"mainFK,omitempty"`
	PriceListFK     int32     `json:"priceListFK,omitempty"`
	CartType        string    `json:"cartType,omitempty"`
	StartDate       time.Time `json:"startDate,omitempty"`
	EndDate         time.Time `json:"endDate,omitempty"`
	MainOrderTypePK int32     `json:"mainOrderTypePK,omitempty"`
	MinOrderTotal   float64   `json:"minOrderTotal,omitempty"`
}
