/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JeunesseProfileCoreDashboardsModelsSmartMobileContactCountsApiResponseModel struct {
	Year          int32 `json:"year,omitempty"`
	Month         int32 `json:"month,omitempty"`
	MonthYear     int32 `json:"monthYear,omitempty"`
	ContactTypeID int32 `json:"contactTypeID,omitempty"`
	Count         int32 `json:"count,omitempty"`
}
