/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

import (
	"time"
)

type JeunesseProfileCoreUsersModelsUserRecognitionModel struct {
	MainPk                    int32     `json:"mainPk,omitempty"`
	Phrase                    string    `json:"phrase,omitempty"`
	Bio                       string    `json:"bio,omitempty"`
	ImageLink                 string    `json:"imageLink,omitempty"`
	RecognitionName           string    `json:"recognitionName,omitempty"`
	IsActive                  bool      `json:"isActive,omitempty"`
	MemberStatus              string    `json:"memberStatus,omitempty"`
	HighestNormalizedRank     int32     `json:"highestNormalizedRank,omitempty"`
	HighestNormalizedRankName string    `json:"highestNormalizedRankName,omitempty"`
	HighestAchievedRankDate   time.Time `json:"highestAchievedRankDate,omitempty"`
}
