/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreRepSiteModelsDiscountCodeViewModel struct {
	DiscountCode string `json:"discountCode,omitempty"`
	MainPK       int32  `json:"mainPK,omitempty"`
	SiteUrl      string `json:"siteUrl,omitempty"`
	Translation  string `json:"translation,omitempty"`
}
