/*
 * Profile-Api v1.0
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package profile_v1

type JeunesseProfileCoreWalletModelsEftEftLocalFormModel struct {
	MainBankAccountPK int32  `json:"mainBankAccountPK,omitempty"`
	BranchName        string `json:"branchName,omitempty"`
	BankNotify        int32  `json:"bankNotify,omitempty"`
	Active            bool   `json:"active,omitempty"`
	AccountCurrency   string `json:"accountCurrency,omitempty"`
	NameAccount       string `json:"nameAccount,omitempty"`
	AccountNumber     string `json:"accountNumber,omitempty"`
	AccountType       int32  `json:"accountType,omitempty"`
	BankCode          string `json:"bankCode,omitempty"`
	BankName          string `json:"bankName,omitempty"`
	BankCountry       string `json:"bankCountry,omitempty"`
	BankSort          string `json:"bankSort,omitempty"`
	BankAddress1      string `json:"bankAddress1,omitempty"`
	BranchCode        string `json:"branchCode,omitempty"`
	Iban              string `json:"iban,omitempty"`
	RoutingNumber     string `json:"routingNumber,omitempty"`
	SwiftBic          string `json:"swift_bic,omitempty"`
}
