CREATE TABLE IF NOT EXISTS orders
(
    id                         bigserial PRIMARY KEY,
    created_at                 timestamp(0) with time zone NOT NULL DEFAULT NOW(),

    -- Unique external identifier from Riman
    main_orders_pk             integer UNIQUE              NOT NULL,

    -- Fields from riman.RimanOrder
    order_date                 text,
    order_type                 text,
    final_order_type           jsonb,
    site_url                   text,
    enc_order_number           text,
    currency_symbol            text,
    currency_code              text,
    paid_status                boolean,
    has_tax_invoice            boolean,
    has_commercial_invoice     boolean,
    has_credit_note            boolean,
    is_shipping_pending        boolean,
    is_pb                      boolean,
    is_pa                      boolean,
    is_cc                      boolean,
    main_fk                    integer,
    main_order_type_fk         integer,
    voucher_url                jsonb,
    ship_country               text,
    shipping_status            text,
    order_shipping_status      text,
    order_type_value           jsonb,
    paid_status_value          text,
    quantity                   integer,
    email                      jsonb,
    phone                      jsonb,
    ship_first_name            jsonb,
    ship_last_name             jsonb,
    marked_paid_date           text,
    total                      double precision,
    conv_total                 double precision,
    conv_total_format          text,
    sub_total                  integer,
    conv_subtotal              integer,
    ship_total                 double precision,
    conv_ship_total            double precision,
    taxes                      double precision,
    tax_label                  text,
    product_tax                double precision,
    shipping_tax               double precision,
    total_product_tax          double precision,
    additional_tax_label       text,
    additional_tax             jsonb,
    conv_taxes                 double precision,
    order_processing_fees      jsonb,
    conv_order_processing_fees jsonb,
    discount                   integer,
    conv_discount              integer,
    refund_amount              integer,
    conv_refund                integer,
    sales_campaign_fk          jsonb,
    paidstatusfk               integer,
    delivery_date              jsonb,
    shipping_details           jsonb,
    order_items                jsonb,
    payments                   jsonb,
    is_prepaid_order           jsonb,
    show_invoice               boolean,
    show_order_invoice         boolean,
    kr_guarantee_no            text,
    we_chat_order_number       jsonb,
    member_id                  jsonb,

    version                    integer                     NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS orders_enc_order_number_idx ON orders (enc_order_number);
