package main

func RepSite_GetRepsiteInfo()              {}
func RepSite_InvalidateRepSiteInfo()       {}
func RepSite_GetRepSiteMainPk()            {}
func RepSite_GetAdWords()                  {}
func RepSite_GetImpressumInfo()            {}
func RepSite_GetDistributorDiscountCodes() {}
func RepSite_SendReferrerEmail()           {}
func RepSite_AddLead()                     {}
func RepSite_ValidateSiteUrl()             {}

func Member_GetPaymentDetails()                {}
func Member_CreatePaymentMethod()              {}
func Member_UpdatePaymentDetails()             {}
func Member_GetHighestRealRank()               {}
func Member_GetMemberInfo()                    {}
func Member_UserAlertCheck()                   {}
func Member_GetUserUnreadCounts()              {}
func Member_RequiresCvv()                      {}
func Member_GetBillingAddress()                {}
func Member_UpdateBillingAddress()             {}
func Member_PayPalAgreementAvailable()         {}
func Member_SendImsEmailToUser()               {}
func Member_IsIxoPayActiveForGateway()         {}
func Member_GetTWUnifiedDonationOrgOptions()   {}
func Member_GetReferrer()                      {}
func Member_SetReferrer()                      {}
func Member_GetUpgradeLink()                   {}
func Member_GetShippingAddress()               {}
func Member_UpdateShippingAddress()            {}
func Member_GetTWUnifiedInfo()                 {}
func Member_InsertUpdateTWUnifiedInfo()        {}
func Member_GetAddressLookUp()                 {}
func Member_VerifyCpf()                        {}
func Member_BonusCreditsGoingToExpire()        {}
func Member_SendSmsMessage()                   {}
func Member_Upgrade()                          {}
func Member_UpdatePassword()                   {}
func Member_UpdatePaymentOrder()               {}
func Member_UpdateShowWelcome()                {}
func Member_RemovePaymentMethod()              {}
func Member_UpdateIsShippingAddress()          {}
func Member_CreateMember()                     {}
func Member_UpdateTOSStatus()                  {}
func Member_ConvertAnonymousMemberToCustomer() {}
func Member_SetMemberPriceList()               {}
func Member_CreateTicket()                     {}
func Member_ValidateSiteUrl()                  {}
func Member_CreateMemberFromEventGuest()       {}
func Member_SetEmailAndPassword()              {}
