package main

func Wallet_GetWalletSettings()            {}
func Wallet_GetPayCardState()              {}
func Wallet_GetPayCardReplaceState()       {}
func Wallet_ReplacePayCard()               {}
func Wallet_GetUserPaymentMethods()        {}
func Wallet_GetIPayoutCardsBin()           {}
func Wallet_GetAccountDetails()            {}
func Wallet_GetPhotoIdData()               {}
func Wallet_UpdatePhotoIdData()            {}
func Wallet_GetUserBankBook()              {}
func Wallet_UpdateUserBankBook()           {}
func Wallet_GetUserBankDocument()          {}
func Wallet_UpdateUserBankDocument()       {}
func Wallet_GetEFTLocalStatus()            {}
func Wallet_GetPersonalInfo()              {}
func Wallet_GetAccountCurrencies()         {}
func Wallet_GetFundRequestCheckRuns()      {}
func Wallet_GetPersonalInfoLocal()         {}
func Wallet_GetFundsRequestSettings()      {}
func Wallet_GetUserPayoutMethods()         {}
func Wallet_GetEFTRequiredDocuments()      {}
func Wallet_GetIdentificationTypes()       {}
func Wallet_GetBankCountries()             {}
func Wallet_GetWalletBalance()             {}
func Wallet_GetFundRequestInvoiceDetails() {}
func Wallet_GetFundsRequest()              {}
func Wallet_CreateFundRequest()            {}
func Wallet_GetAccountHistory()            {}
func Wallet_GetSignupTokens()              {}
func Wallet_CreateSignupToken()            {}
func Wallet_RegisterPaycard()              {}
func Wallet_AddFundsGetRedirectUrl()       {}
func Wallet_AdminUpdatePhotoIdData()       {}
func Wallet_GetPayCardValidation()         {}
func Wallet_GetEWalletLoginForm()          {}
func Wallet_UpdateUserFundRequestInvoice() {}
func Wallet_SaveEFTBankInfo()              {}
func Wallet_DeactivateBankAccount()        {}
func Wallet_UpdateUserPayoutMethods()      {}
func Wallet_ResetWalletPassword()          {}
func Wallet_SaveEFTLocalBankInfo()         {}
func Wallet_DeleteSignupToken()            {}
func Wallet_DeleteFundRequest()            {}

func WalletMember_GetSecurityQuestions() {}
func WalletMember_GetQuestionsList()     {}
func WalletMember_SetQuestions()         {}
func WalletMember_CheckAttempts()        {}
func WalletMember_CreateWalletAccount()  {}
func WalletMember_GetResetCode()         {}
func WalletMember_ResetPassword()        {}
func WalletMember_UpdatePassword()       {}
