/*
 * Cart-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v2

type ShippingQueryModel struct {
	CartKey     string `json:"cartKey,omitempty"`
	Address1    string `json:"address1,omitempty"`
	Address2    string `json:"address2,omitempty"`
	Address3    string `json:"address3,omitempty"`
	Country     string `json:"country,omitempty"`
	State       string `json:"state,omitempty"`
	Zip         string `json:"zip,omitempty"`
	City        string `json:"city,omitempty"`
	MainPk      int32  `json:"mainPk,omitempty"`
	IsPOBox     bool   `json:"isPOBox,omitempty"`
	MainOrderPK int32  `json:"mainOrderPK,omitempty"`
	IsSDProfile bool   `json:"isSDProfile,omitempty"`
	IsAdmin     bool   `json:"isAdmin,omitempty"`
	IsEvent     bool   `json:"isEvent,omitempty"`
}
