/*
 * Cart-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v2

type UpdateOrderShipAddressFormModel struct {
	MainOrdersFK            int32  `json:"mainOrdersFK,omitempty"`
	FirstName               string `json:"firstName"`
	LastName                string `json:"lastName"`
	Address1                string `json:"address1"`
	Address2                string `json:"address2,omitempty"`
	Address3                string `json:"address3,omitempty"`
	City                    string `json:"city"`
	State                   string `json:"state"`
	PostalCode              string `json:"postalCode,omitempty"`
	Country                 string `json:"country"`
	Area                    string `json:"area,omitempty"`
	IsResidential           bool   `json:"isResidential,omitempty"`
	Email                   string `json:"email,omitempty"`
	Phone                   string `json:"phone,omitempty"`
	Fax                     string `json:"fax,omitempty"`
	VerifiedShippingAddress bool   `json:"verifiedShippingAddress,omitempty"`
}
