/*
 * Cart-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v2

type BrandViewModel struct {
	ItemPK                 int32  `json:"itemPK,omitempty"`
	Name                   string `json:"name,omitempty"`
	TranslationState       string `json:"translationState,omitempty"`
	TranslationName        string `json:"translationName,omitempty"`
	Summary                string `json:"summary,omitempty"`
	Description            string `json:"description,omitempty"`
	ImageUrl               string `json:"imageUrl,omitempty"`
	SpotlightSmallImage    string `json:"spotlightSmallImage,omitempty"`
	SpotlightSmallImageKey string `json:"spotlightSmallImageKey,omitempty"`
	SpotlightLargeImage    string `json:"spotlightLargeImage,omitempty"`
	SpotlightLargeImageKey string `json:"spotlightLargeImageKey,omitempty"`
	BannerImage            string `json:"bannerImage,omitempty"`
	BannerImageKey         string `json:"bannerImageKey,omitempty"`
}
