/*
 * Cart-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v2

type ProductPricingViewModel struct {
	PriceType      string  `json:"priceType,omitempty"`
	CurrencySymbol string  `json:"currencySymbol,omitempty"`
	Price          float64 `json:"price,omitempty"`
	NoVatPrice     float64 `json:"noVatPrice,omitempty"`
	FormattedPrice string  `json:"formattedPrice,omitempty"`
	PriceWarning   string  `json:"priceWarning,omitempty"`
}
