/*
 * Cart-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v2

type BestSellersViewModel struct {
	ProductPK              int32                 `json:"productPK,omitempty"`
	Name                   string                `json:"name,omitempty"`
	ImageUrl               string                `json:"imageUrl,omitempty"`
	Description            string                `json:"description,omitempty"`
	Price                  string                `json:"price,omitempty"`
	AltPrice               string                `json:"altPrice,omitempty"`
	ProductMenu            string                `json:"productMenu,omitempty"`
	SpotlightSmallImageKey string                `json:"spotlightSmallImageKey,omitempty"`
	SpotlightLargeImageKey string                `json:"spotlightLargeImageKey,omitempty"`
	Product                *FullProductViewModel `json:"product,omitempty"`
}
