/*
 * Cart-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v2

type PackComponentModel struct {
	ProductPK   int32  `json:"productPK,omitempty"`
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	ImgUrl      string `json:"imgUrl,omitempty"`
	Qty         int32  `json:"qty,omitempty"`
}
