/*
 * Cart-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v2

type ProductSearchViewModel struct {
	ProductFK   int32  `json:"productFK,omitempty"`
	ProductName string `json:"productName,omitempty"`
	ImageUrl    string `json:"imageUrl,omitempty"`
}
