/*
 * Cart-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v2

type CategoryModel struct {
	Id             int32               `json:"id,omitempty"`
	Name           string              `json:"name,omitempty"`
	Description    string              `json:"description,omitempty"`
	ImageUrl       string              `json:"imageUrl,omitempty"`
	ImageKey       string              `json:"imageKey,omitempty"`
	BannerImageUrl string              `json:"bannerImageUrl,omitempty"`
	BannerImageKey string              `json:"bannerImageKey,omitempty"`
	SeqNo          float32             `json:"seqNo,omitempty"`
	TranslationKey string              `json:"translationKey,omitempty"`
	HasSubMenu     bool                `json:"hasSubMenu,omitempty"`
	IsBranded      bool                `json:"isBranded,omitempty"`
	ShowInTopMenu  bool                `json:"showInTopMenu,omitempty"`
	Menus          []SubMenuBlockModel `json:"menus,omitempty"`
}
