/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type OrderCompleteModel struct {
	MainOrderPk       int32   `json:"mainOrderPk"`
	SecurityCode      string  `json:"securityCode,omitempty"`
	InAuthId          string  `json:"inAuthId,omitempty"`
	Amount            float64 `json:"amount,omitempty"`
	Source            string  `json:"source,omitempty"`
	PaymentMethodCode string  `json:"paymentMethodCode,omitempty"`
	PaymentType       string  `json:"paymentType"`
	Card3DSTokenType  string  `json:"card3DSTokenType,omitempty"`
}
