/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type DonationReportViewModel struct {
	Mainorderspk   int32     `json:"mainorderspk,omitempty"`
	Quantity       int32     `json:"quantity,omitempty"`
	Orderdate      time.Time `json:"orderdate,omitempty"`
	CurrencySymbol string    `json:"currencySymbol,omitempty"`
	Currencyrate   float64   `json:"currencyrate,omitempty"`
	Price          float64   `json:"price,omitempty"`
	PaymentMethod  string    `json:"paymentMethod,omitempty"`
	Type_          string    `json:"type,omitempty"`
	Shipto         string    `json:"shipto,omitempty"`
	StringPrice    string    `json:"stringPrice,omitempty"`
	Description    string    `json:"description,omitempty"`
}
