/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type SmartDeliveryItemConfigViewModel struct {
	AutoshipOrderItemsFK int32  `json:"autoshipOrderItemsFK,omitempty"`
	AutoshipOrderFK      int32  `json:"autoshipOrderFK,omitempty"`
	ProductFK            int32  `json:"productFK,omitempty"`
	ConfigProductFK      int32  `json:"configProductFK,omitempty"`
	PackageFK            int32  `json:"packageFK,omitempty"`
	ProductName          string `json:"productName,omitempty"`
	ImageUrl             string `json:"imageUrl,omitempty"`
}
