/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type AvailableCouponModel struct {
	MainPK             int32   `json:"mainPK,omitempty"`
	DiscountCode       string  `json:"discountCode,omitempty"`
	MaxCouponAmount    float64 `json:"maxCouponAmount,omitempty"`
	DiscountPercentage float64 `json:"discountPercentage,omitempty"`
	ProductPK          int32   `json:"productPK,omitempty"`
	CouponDetail       string  `json:"couponDetail,omitempty"`
}
