/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type MainOrderItemModel struct {
	MainOrderItemsPK     int32     `json:"mainOrderItemsPK"`
	MainOrdersPK         int32     `json:"mainOrdersPK,omitempty"`
	MainFK               int32     `json:"mainFK"`
	ProductPK            int32     `json:"productPK"`
	Product              string    `json:"product"`
	UsProduct            string    `json:"usProduct,omitempty"`
	Quantity             int32     `json:"quantity,omitempty"`
	ShippingStatus       string    `json:"shippingStatus"`
	ShippingCompany      string    `json:"shippingCompany,omitempty"`
	ShippingDate         time.Time `json:"shippingDate,omitempty"`
	TaxCodeFK            string    `json:"taxCodeFK,omitempty"`
	CurrencyRate         float64   `json:"currencyRate,omitempty"`
	CurrencySymbol       string    `json:"currencySymbol,omitempty"`
	ProductsCategoryFK   int32     `json:"productsCategoryFK,omitempty"`
	UnitPrice            float64   `json:"unitPrice,omitempty"`
	Price                float64   `json:"price,omitempty"`
	ConvertedPrice       float64   `json:"convertedPrice,omitempty"`
	ConvertedPriceFormat string    `json:"convertedPriceFormat,omitempty"`
	Vat                  float64   `json:"vat,omitempty"`
	Taxes                float64   `json:"taxes,omitempty"`
	ShipTotal            float64   `json:"shipTotal,omitempty"`
	RetailPrice          float64   `json:"retailPrice,omitempty"`
	IsTaxable            bool      `json:"isTaxable,omitempty"`
	TaxableTotal         float64   `json:"taxableTotal,omitempty"`
	ProductCode          string    `json:"productCode,omitempty"`
	IsShippable          bool      `json:"isShippable,omitempty"`
	ProductPrice         float64   `json:"productPrice,omitempty"`
	TrackingNumber       string    `json:"trackingNumber,omitempty"`
	OrderCode            string    `json:"orderCode,omitempty"`
	PaymentMethod        string    `json:"paymentMethod,omitempty"`
	CurrencyCode         string    `json:"currencyCode,omitempty"`
	ImageUrl             string    `json:"imageUrl,omitempty"`
	SetUpForAS           bool      `json:"setUpForAS,omitempty"`
	Cv                   float64   `json:"cv,omitempty"`
	Sp                   float64   `json:"sp,omitempty"`
}
