/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type ProductConfigurationFormModel struct {
	CartType       string `json:"cartType,omitempty"`
	CountryCode    string `json:"countryCode,omitempty"`
	ProductPK      int32  `json:"productPK,omitempty"`
	LanguageID     int32  `json:"languageID,omitempty"`
	SiteUrl        string `json:"siteUrl,omitempty"`
	IsPackage      bool   `json:"isPackage,omitempty"`
	IsConfigurable bool   `json:"isConfigurable,omitempty"`
}
