/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type SalesCampaignModel struct {
	SalesCampaignPK      int32                       `json:"salesCampaignPK,omitempty"`
	MainFK               int32                       `json:"mainFK,omitempty"`
	CreatedDate          time.Time                   `json:"createdDate,omitempty"`
	StartDate            time.Time                   `json:"startDate,omitempty"`
	EndDate              time.Time                   `json:"endDate,omitempty"`
	Name                 string                      `json:"name"`
	PriceListFK          int32                       `json:"priceListFK,omitempty"`
	CampaignCode         string                      `json:"campaignCode,omitempty"`
	ProductBrandFK       int32                       `json:"productBrandFK,omitempty"`
	CcapConfigFK         int32                       `json:"ccapConfigFK,omitempty"`
	Products             []SalesCampaignProductModel `json:"products,omitempty"`
	CampaignUrl          string                      `json:"campaignUrl,omitempty"`
	CampaignImageUrl     string                      `json:"campaignImageUrl,omitempty"`
	IsCampaignExpired    bool                        `json:"isCampaignExpired,omitempty"`
	SupportsDiscountCode bool                        `json:"supportsDiscountCode,omitempty"`
}
