/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type PaymentOrderProcessingFeeModel struct {
	PaymentMethodCode string  `json:"paymentMethodCode,omitempty"`
	NoOfInstallments  int32   `json:"noOfInstallments,omitempty"`
	SurchargeRate     float64 `json:"surchargeRate,omitempty"`
	LangText          string  `json:"langText,omitempty"`
}
