/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type OrderConfirmationDetailViewModel struct {
	MainOrderPK                  int32                 `json:"mainOrderPK,omitempty"`
	MainOrdersPK                 int32                 `json:"mainOrdersPK,omitempty"`
	EncOrderNumber               string                `json:"encOrderNumber,omitempty"`
	MainPk                       int32                 `json:"mainPk,omitempty"`
	MainTypeFK                   int32                 `json:"mainTypeFK,omitempty"`
	MainOrderTypeFK              int32                 `json:"mainOrderTypeFK,omitempty"`
	AccountCreated               bool                  `json:"accountCreated,omitempty"`
	CountryCode                  string                `json:"countryCode,omitempty"`
	SubTotal                     float64               `json:"subTotal,omitempty"`
	FormattedSubTotal            string                `json:"formattedSubTotal,omitempty"`
	Total                        float64               `json:"total,omitempty"`
	ProductTax                   float64               `json:"productTax,omitempty"`
	ShippingTax                  float64               `json:"shippingTax,omitempty"`
	TotalProductTax              float64               `json:"totalProductTax,omitempty"`
	AdditionalTax                float64               `json:"additionalTax,omitempty"`
	AdditionalTaxLabel           string                `json:"additionalTaxLabel,omitempty"`
	UsdTotal                     float64               `json:"usdTotal,omitempty"`
	FormattedTotal               string                `json:"formattedTotal,omitempty"`
	Discount                     float64               `json:"discount,omitempty"`
	FormattedDiscount            string                `json:"formattedDiscount,omitempty"`
	Taxes                        float64               `json:"taxes,omitempty"`
	TaxLabel                     string                `json:"taxLabel,omitempty"`
	FormattedTaxes               string                `json:"formattedTaxes,omitempty"`
	FormattedProductTax          string                `json:"formattedProductTax,omitempty"`
	FormattedShippingTax         string                `json:"formattedShippingTax,omitempty"`
	FormattedTotalProductTax     string                `json:"formattedTotalProductTax,omitempty"`
	FormattedAdditionalTax       string                `json:"formattedAdditionalTax,omitempty"`
	FormattedOrderProcessingFees string                `json:"formattedOrderProcessingFees,omitempty"`
	Shipping                     float64               `json:"shipping,omitempty"`
	FormattedShipping            string                `json:"formattedShipping,omitempty"`
	OrderProcessingFees          float64               `json:"orderProcessingFees,omitempty"`
	ShippingTypeFK               int32                 `json:"shippingTypeFK,omitempty"`
	HasPromo                     bool                  `json:"hasPromo,omitempty"`
	PaymentType                  string                `json:"paymentType,omitempty"`
	CcType                       string                `json:"ccType,omitempty"`
	CcNumberLastFour             string                `json:"ccNumberLastFour,omitempty"`
	RuCode                       string                `json:"ruCode,omitempty"`
	ShipState                    string                `json:"shipState,omitempty"`
	ShipZip                      string                `json:"shipZip,omitempty"`
	ShipCity                     string                `json:"shipCity,omitempty"`
	ShipAddress3                 string                `json:"shipAddress3,omitempty"`
	ShipAddress2                 string                `json:"shipAddress2,omitempty"`
	ShipAddress                  string                `json:"shipAddress,omitempty"`
	ShipLastName                 string                `json:"shipLastName,omitempty"`
	ShipFirstName                string                `json:"shipFirstName,omitempty"`
	ShipCountry                  string                `json:"shipCountry,omitempty"`
	BillingState                 string                `json:"billingState,omitempty"`
	BillingZip                   string                `json:"billingZip,omitempty"`
	BillingCity                  string                `json:"billingCity,omitempty"`
	BillingAddress3              string                `json:"billingAddress3,omitempty"`
	BillingAddress2              string                `json:"billingAddress2,omitempty"`
	BillingAddress               string                `json:"billingAddress,omitempty"`
	BillingFirstName             string                `json:"billingFirstName,omitempty"`
	BillingLastName              string                `json:"billingLastName,omitempty"`
	BillingName                  string                `json:"billingName,omitempty"`
	BillingCountry               string                `json:"billingCountry,omitempty"`
	PhoneNumber                  string                `json:"phoneNumber,omitempty"`
	Email                        string                `json:"email,omitempty"`
	Status                       string                `json:"status,omitempty"`
	CurrencyCode                 string                `json:"currencyCode,omitempty"`
	CurrencySymbol               string                `json:"currencySymbol,omitempty"`
	CurrencyRate                 float64               `json:"currencyRate,omitempty"`
	PaidStatus                   bool                  `json:"paidStatus,omitempty"`
	PaidStatusFk                 int32                 `json:"paidStatusFk,omitempty"`
	RetailSignup                 bool                  `json:"retailSignup,omitempty"`
	RetailStarterKit             bool                  `json:"retailStarterKit,omitempty"`
	EventTitle                   string                `json:"eventTitle,omitempty"`
	EventUrl                     string                `json:"eventUrl,omitempty"`
	OfferLoyaltyProgram          bool                  `json:"offerLoyaltyProgram,omitempty"`
	ShippingInstructions         string                `json:"shippingInstructions,omitempty"`
	DeliveryDate                 time.Time             `json:"deliveryDate,omitempty"`
	ShowFISCALink                bool                  `json:"showFISCALink,omitempty"`
	ShowMicroEntrFISCALink       bool                  `json:"showMicroEntrFISCALink,omitempty"`
	IsVolumeBasedRSB             bool                  `json:"isVolumeBasedRSB,omitempty"`
	DeliverySlot                 string                `json:"deliverySlot,omitempty"`
	IsImportOrder                bool                  `json:"isImportOrder,omitempty"`
	Items                        []OrderItemsViewModel `json:"items,omitempty"`
	Payments                     []OrderPayments       `json:"payments,omitempty"`
	DiscountDetails              []Discount            `json:"discountDetails,omitempty"`
	PaymentStatus                *PaymentStatus        `json:"paymentStatus,omitempty"`
	ThTaxInvoiceNumber           string                `json:"thTaxInvoiceNumber,omitempty"`
	KrGuaranteeNo                string                `json:"krGuaranteeNo,omitempty"`
	ShowMYeSigDeclaration        bool                  `json:"showMYeSigDeclaration,omitempty"`
}
