/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type PaymentProcessingResponse struct {
	PaymentMethodPK            int32                      `json:"paymentMethodPK,omitempty"`
	PaymentMethodTypePK        int32                      `json:"paymentMethodTypePK,omitempty"`
	AmountProcessed            float64                    `json:"amountProcessed,omitempty"`
	Approved                   bool                       `json:"approved,omitempty"`
	AmountPaid                 float64                    `json:"amountPaid,omitempty"`
	Balance                    float64                    `json:"balance,omitempty"`
	SplitComplete              bool                       `json:"splitComplete,omitempty"`
	PaidStatusFK               int32                      `json:"paidStatusFK,omitempty"`
	IsSplitTender              bool                       `json:"isSplitTender,omitempty"`
	PendingPaid                float64                    `json:"pendingPaid,omitempty"`
	ProcessedFee               float64                    `json:"processedFee,omitempty"`
	CurrencyRatesFK            string                     `json:"currencyRatesFK,omitempty"`
	CurrencyCode               string                     `json:"currencyCode,omitempty"`
	CurrencySymbol             string                     `json:"currencySymbol,omitempty"`
	CurrencyRate               float64                    `json:"currencyRate,omitempty"`
	MerchantOrderProcessStatus string                     `json:"merchantOrderProcessStatus,omitempty"`
	HasErrorTranslation        bool                       `json:"hasErrorTranslation,omitempty"`
	CmsErrorTranslationName    string                     `json:"cmsErrorTranslationName,omitempty"`
	IsAppliedAsPaymentMethod   bool                       `json:"isAppliedAsPaymentMethod,omitempty"`
	PaidStatus                 bool                       `json:"paidStatus,omitempty"`
	ResponseText               string                     `json:"responseText,omitempty"`
	GtwCode                    string                     `json:"gtwCode,omitempty"`
	GtwAccount                 string                     `json:"gtwAccount,omitempty"`
	AuthFormRequired           bool                       `json:"authFormRequired,omitempty"`
	Successful                 bool                       `json:"successful,omitempty"`
	IsRedirect                 bool                       `json:"isRedirect,omitempty"`
	RedirectUrl                string                     `json:"redirectUrl,omitempty"`
	RedirectType               string                     `json:"redirectType,omitempty"`
	ValidationMessage          string                     `json:"validationMessage,omitempty"`
	RedirectModel              *MerchantRedirectViewModel `json:"redirectModel,omitempty"`
}
