/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type CartItemViewModel struct {
	Id                          int32               `json:"id,omitempty"`
	Quantity                    int32               `json:"quantity,omitempty"`
	ProductFk                   int32               `json:"productFk,omitempty"`
	PackageFk                   int32               `json:"packageFk,omitempty"`
	Name                        string              `json:"name,omitempty"`
	ImageUrl                    string              `json:"imageUrl,omitempty"`
	SetupForAs                  bool                `json:"setupForAs,omitempty"`
	ConfigFk                    int32               `json:"configFk,omitempty"`
	PriceListFk                 int32               `json:"priceListFk,omitempty"`
	IsPaCItem                   bool                `json:"isPaCItem,omitempty"`
	IsSignup                    bool                `json:"isSignup,omitempty"`
	Sku                         string              `json:"sku,omitempty"`
	PriceType                   string              `json:"priceType,omitempty"`
	CountryCode                 string              `json:"countryCode,omitempty"`
	CurrencyPK                  int32               `json:"currencyPK,omitempty"`
	CurrencyCode                string              `json:"currencyCode,omitempty"`
	CurrencySymbol              string              `json:"currencySymbol,omitempty"`
	ExtraFee                    string              `json:"extraFee,omitempty"`
	Discount                    float64             `json:"discount,omitempty"`
	FormattedDiscount           string              `json:"formattedDiscount,omitempty"`
	BasePrice                   float64             `json:"basePrice,omitempty"`
	FormattedBasePrice          string              `json:"formattedBasePrice,omitempty"`
	UnitPrice                   float64             `json:"unitPrice,omitempty"`
	FormattedUnitPrice          string              `json:"formattedUnitPrice,omitempty"`
	RetailTaxablePrice          float64             `json:"retailTaxablePrice,omitempty"`
	FormattedRetailTaxablePrice string              `json:"formattedRetailTaxablePrice,omitempty"`
	Cv                          float64             `json:"cv,omitempty"`
	Sp                          float64             `json:"sp,omitempty"`
	MaxLimit                    int32               `json:"maxLimit,omitempty"`
	Points                      float64             `json:"points,omitempty"`
	IsShippable                 bool                `json:"isShippable,omitempty"`
	IsStarterKit                bool                `json:"isStarterKit,omitempty"`
	BrandName                   string              `json:"brandName,omitempty"`
	LineSubTotal                float64             `json:"lineSubTotal,omitempty"`
	FormattedLineSubTotal       string              `json:"formattedLineSubTotal,omitempty"`
	LineTotal                   float64             `json:"lineTotal,omitempty"`
	FormattedLineTotal          string              `json:"formattedLineTotal,omitempty"`
	OfferAffiliateProgram       bool                `json:"offerAffiliateProgram,omitempty"`
	IsVolumeBasedRSB            bool                `json:"isVolumeBasedRSB,omitempty"`
	OfferPreferredCust          bool                `json:"offerPreferredCust,omitempty"`
	OfferLoyaltyProgram         bool                `json:"offerLoyaltyProgram,omitempty"`
	ShowSDCheckbox              bool                `json:"showSDCheckbox,omitempty"`
	JoinMaxLifetimeLimitCatCode string              `json:"joinMaxLifetimeLimitCatCode,omitempty"`
	JoinMaxLifetimeLimit        int32               `json:"joinMaxLifetimeLimit,omitempty"`
	ChildItems                  []CartItemViewModel `json:"childItems,omitempty"`
}
