/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type AddressValidationModel struct {
	Status           int32     `json:"status,omitempty"`
	SimilarAddresses []Address `json:"similarAddresses,omitempty"`
}
