/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type PrepaidPbOrderModel struct {
	Id                int32                     `json:"id,omitempty"`
	MainFK            int32                     `json:"mainFK,omitempty"`
	MainOrdersFK      int32                     `json:"mainOrdersFK,omitempty"`
	PrepaidStatus     string                    `json:"prepaidStatus,omitempty"`
	StartDate         time.Time                 `json:"startDate,omitempty"`
	EndDate           time.Time                 `json:"endDate,omitempty"`
	NextProcessDate   time.Time                 `json:"nextProcessDate,omitempty"`
	CreatedDate       time.Time                 `json:"createdDate,omitempty"`
	NoOfPrepaidMonths int32                     `json:"noOfPrepaidMonths,omitempty"`
	MonthlyBV         int32                     `json:"monthlyBV,omitempty"`
	TotalBV           int32                     `json:"totalBV,omitempty"`
	MinDate           time.Time                 `json:"minDate,omitempty"`
	SubPA             []PrepaidPaOrderViewModel `json:"subPA,omitempty"`
}
