/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type OrderInfoItemModel struct {
	ProductPK     int32   `json:"productPK,omitempty"`
	ProductName   string  `json:"productName,omitempty"`
	ProductCode   string  `json:"productCode,omitempty"`
	Quantity      int32   `json:"quantity,omitempty"`
	UnitPrice     float64 `json:"unitPrice,omitempty"`
	Price         float64 `json:"price,omitempty"`
	Discount      float64 `json:"discount,omitempty"`
	CampaignPrice float64 `json:"campaignPrice,omitempty"`
	UnitCV        int32   `json:"unitCV,omitempty"`
	Cv            int32   `json:"cv,omitempty"`
	SetupForAS    bool    `json:"setupForAS,omitempty"`
}
