/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type OrderPayments struct {
	MainOrdersFK        int32     `json:"mainOrdersFK,omitempty"`
	PaymentMethodCode   string    `json:"paymentMethodCode,omitempty"`
	RefundTotal         float64   `json:"refundTotal,omitempty"`
	RefundTotalFormat   string    `json:"refundTotalFormat,omitempty"`
	CurrencyCode        string    `json:"currencyCode,omitempty"`
	PaymentMethod       string    `json:"paymentMethod,omitempty"`
	PaymentAmount       float64   `json:"paymentAmount,omitempty"`
	PaymentAmountFormat string    `json:"paymentAmountFormat,omitempty"`
	CurrencySymbol      string    `json:"currencySymbol,omitempty"`
	Refsiteurl          string    `json:"refsiteurl,omitempty"`
	PaymentMethodPK     int32     `json:"paymentMethodPK,omitempty"`
	PaidStatusFK        int32     `json:"paidStatusFK,omitempty"`
	PaymentTimeStamp    time.Time `json:"paymentTimeStamp,omitempty"`
	OrderTimeStamp      time.Time `json:"orderTimeStamp,omitempty"`
	AcStatus            string    `json:"acStatus,omitempty"`
	CcNumberLastFour    string    `json:"ccNumberLastFour,omitempty"`
	CcType              string    `json:"ccType,omitempty"`
	CcExp               string    `json:"ccExp,omitempty"`
	InstallmentPayments int32     `json:"installmentPayments,omitempty"`
	Address             string    `json:"address,omitempty"`
	Address2            string    `json:"address2,omitempty"`
	Address3            string    `json:"address3,omitempty"`
	City                string    `json:"city,omitempty"`
	State               string    `json:"state,omitempty"`
	Country             string    `json:"country,omitempty"`
	Zip                 string    `json:"zip,omitempty"`
}
