/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type RmaViewModel struct {
	Id             int32     `json:"id,omitempty"`
	RmaNumber      int32     `json:"rmaNumber,omitempty"`
	CustomerID     int32     `json:"customerID,omitempty"`
	OrderID        int32     `json:"orderID,omitempty"`
	AdminID        int32     `json:"adminID,omitempty"`
	Status         string    `json:"status,omitempty"`
	StatusID       int32     `json:"statusID,omitempty"`
	IssueDate      time.Time `json:"issueDate,omitempty"`
	RecivedDate    time.Time `json:"recivedDate,omitempty"`
	RefundDate     time.Time `json:"refundDate,omitempty"`
	ReasonID       int32     `json:"reasonID,omitempty"`
	Reason         string    `json:"reason,omitempty"`
	SiteURL        string    `json:"siteURL,omitempty"`
	CustomerName   string    `json:"customerName,omitempty"`
	DepartmentName string    `json:"departmentName,omitempty"`
	IssuedBy       string    `json:"issuedBy,omitempty"`
	Notes          string    `json:"notes,omitempty"`
}
