/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type MerchantRedirectViewModel struct {
	MainOrdersFK      int32                        `json:"mainOrdersFK,omitempty"`
	PaymentMethodCode string                       `json:"paymentMethodCode,omitempty"`
	RedirectType      string                       `json:"redirectType,omitempty"`
	MerchantParams    []MerchantParamBaseView      `json:"merchantParams,omitempty"`
	Amount            float64                      `json:"amount,omitempty"`
	InitScriptModel   bool                         `json:"initScriptModel,omitempty"`
	HasPendingStatus  bool                         `json:"hasPendingStatus,omitempty"`
	ValidationMessage string                       `json:"validationMessage,omitempty"`
	ScriptModel       *MerchantRedirectScriptModel `json:"scriptModel,omitempty"`
}
