/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type PaymentFormModel struct {
	MainOrdersFK         int32   `json:"mainOrdersFK,omitempty"`
	MainFK               int32   `json:"mainFK,omitempty"`
	PaymentMethodTypePK  int32   `json:"paymentMethodTypePK,omitempty"`
	Amount               float64 `json:"amount,omitempty"`
	SplitPayment         bool    `json:"splitPayment,omitempty"`
	TokenSiteURL         string  `json:"tokenSiteURL,omitempty"`
	Token                string  `json:"token,omitempty"`
	MainCreditCardsPK    int32   `json:"mainCreditCardsPK,omitempty"`
	CardFullName         string  `json:"cardFullName,omitempty"`
	CardNumber           string  `json:"cardNumber,omitempty"`
	CardType             string  `json:"cardType,omitempty"`
	Cvv                  string  `json:"cvv,omitempty"`
	ExpireMonth          string  `json:"expireMonth,omitempty"`
	ExpireYear           string  `json:"expireYear,omitempty"`
	SaveCardInfo         bool    `json:"saveCardInfo,omitempty"`
	Installment          int32   `json:"installment,omitempty"`
	CheckNumber          int32   `json:"checkNumber,omitempty"`
	ManualPayDescription string  `json:"manualPayDescription,omitempty"`
	ManualPayType        int32   `json:"manualPayType,omitempty"`
	TransactionDate      string  `json:"transactionDate,omitempty"`
	InAuthId             string  `json:"inAuthId,omitempty"`
	UseBillingAddress    bool    `json:"useBillingAddress,omitempty"`
	CcBillingFname       string  `json:"ccBillingFname,omitempty"`
	CcBillingLname       string  `json:"ccBillingLname,omitempty"`
	CcBillingAddr1       string  `json:"ccBillingAddr1,omitempty"`
	CcBillingAddr2       string  `json:"ccBillingAddr2,omitempty"`
	CcBillingCity        string  `json:"ccBillingCity,omitempty"`
	CcBillingState       string  `json:"ccBillingState,omitempty"`
	CcBillingZip         string  `json:"ccBillingZip,omitempty"`
	CcBillingCountry     string  `json:"ccBillingCountry,omitempty"`
	CcBillingPhone       string  `json:"ccBillingPhone,omitempty"`
	CcBillingEmail       string  `json:"ccBillingEmail,omitempty"`
	CardToken            string  `json:"cardToken,omitempty"`
}
