/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type PaymentStatus struct {
	AmountPaid      float64 `json:"amountPaid,omitempty"`
	Balance         float64 `json:"balance,omitempty"`
	Complete        bool    `json:"complete,omitempty"`
	Count           int32   `json:"count,omitempty"`
	PendingPaid     float64 `json:"pendingPaid,omitempty"`
	ProcessedFee    float64 `json:"processedFee,omitempty"`
	CurrencyRatesFK string  `json:"currencyRatesFK,omitempty"`
	CurrencyCode    string  `json:"currencyCode,omitempty"`
	CurrencySymbol  string  `json:"currencySymbol,omitempty"`
	CurrencyRate    float64 `json:"currencyRate,omitempty"`
}
