/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type OrderCompleteTokenModel struct {
	PaymentMethodCode string `json:"paymentMethodCode,omitempty"`
	Oncode            string `json:"oncode"`
	Source            string `json:"source,omitempty"`
	Token             string `json:"token,omitempty"`
	UseOrder          string `json:"useOrder,omitempty"`
}
