/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type Splitorders struct {
	MainOrdersFK        int32   `json:"mainOrdersFK,omitempty"`
	PaymentMethodCode   string  `json:"paymentMethodCode,omitempty"`
	RefundTotal         float64 `json:"refundTotal,omitempty"`
	RefundTotalFormat   string  `json:"refundTotalFormat,omitempty"`
	CurrencyCode        string  `json:"currencyCode,omitempty"`
	PaymentMethod       string  `json:"paymentMethod,omitempty"`
	PaymentAmount       float64 `json:"paymentAmount,omitempty"`
	PaymentAmountFormat string  `json:"paymentAmountFormat,omitempty"`
	CurrencySymbol      string  `json:"currencySymbol,omitempty"`
	Refsiteurl          string  `json:"refsiteurl,omitempty"`
}
