/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type MainOrderTrackingModel struct {
	MainOrdersPK         string    `json:"mainOrdersPK"`
	TrackingNumber       string    `json:"trackingNumber,omitempty"`
	Status               string    `json:"status,omitempty"`
	ShipCountry          string    `json:"shipCountry,omitempty"`
	Company              string    `json:"company,omitempty"`
	UpsCode              string    `json:"upsCode,omitempty"`
	ShippingType         string    `json:"shippingType,omitempty"`
	ShippingChartTypesPK int32     `json:"shippingChartTypesPK,omitempty"`
	OrderDate            time.Time `json:"orderDate,omitempty"`
	OrderPackagingInfoPK int32     `json:"orderPackagingInfoPK,omitempty"`
	TrackingLink         string    `json:"trackingLink,omitempty"`
	ShipCompany          string    `json:"shipCompany,omitempty"`
	Email                string    `json:"email,omitempty"`
	Phone                string    `json:"phone,omitempty"`
	ShipFirstName        string    `json:"shipFirstName,omitempty"`
	ShipLastName         string    `json:"shipLastName,omitempty"`
	Address              string    `json:"address,omitempty"`
	City                 string    `json:"city,omitempty"`
	State                string    `json:"state,omitempty"`
	Country              string    `json:"country,omitempty"`
}
