/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

// Credit Card Types request model
type GetCreditCardTypesRequestModel struct {
	// Main Order Type PK for the request
	MainOrderTypeFK int32 `json:"mainOrderTypeFK,omitempty"`
	// Main Order PK for the request
	MainOrderPk int32 `json:"mainOrderPk,omitempty"`
}
