/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type OrderInfoModel struct {
	MainPK                      int32                `json:"mainPK,omitempty"`
	MainOrdersPK                int32                `json:"mainOrdersPK,omitempty"`
	Total                       float64              `json:"total,omitempty"`
	ShippingWon                 float64              `json:"shippingWon,omitempty"`
	TaxableSubtotal             float64              `json:"taxableSubtotal,omitempty"`
	SubTotal                    float64              `json:"subTotal,omitempty"`
	ShippingTypeFK              int32                `json:"shippingTypeFK,omitempty"`
	Discount                    float64              `json:"discount,omitempty"`
	ShipTotal                   float64              `json:"shipTotal,omitempty"`
	Taxes                       float64              `json:"taxes,omitempty"`
	SiteURL                     string               `json:"siteURL,omitempty"`
	ReferrerMainPK              int32                `json:"referrerMainPK,omitempty"`
	ReferrerSiteURL             string               `json:"referrerSiteURL,omitempty"`
	PaidStatus                  bool                 `json:"paidStatus,omitempty"`
	PaidStatusPK                int32                `json:"paidStatusPK,omitempty"`
	PaidStatusName              string               `json:"paidStatusName,omitempty"`
	Refunded                    bool                 `json:"refunded,omitempty"`
	RefundTotal                 float64              `json:"refundTotal,omitempty"`
	MainOrderShippingStatusPK   int32                `json:"mainOrderShippingStatusPK,omitempty"`
	MainOrderShippingStatusName string               `json:"mainOrderShippingStatusName,omitempty"`
	ShipFirstName               string               `json:"shipFirstName,omitempty"`
	ShipLastName                string               `json:"shipLastName,omitempty"`
	ShipAddress                 string               `json:"shipAddress,omitempty"`
	ShipAddress2                string               `json:"shipAddress2,omitempty"`
	ShipAddress3                string               `json:"shipAddress3,omitempty"`
	ShipCity                    string               `json:"shipCity,omitempty"`
	ShipState                   string               `json:"shipState,omitempty"`
	ShipOtherState              string               `json:"shipOtherState,omitempty"`
	ShipZip                     string               `json:"shipZip,omitempty"`
	ShipCountry                 string               `json:"shipCountry,omitempty"`
	Email                       string               `json:"email,omitempty"`
	Phone                       string               `json:"phone,omitempty"`
	MainOrderTypePK             int32                `json:"mainOrderTypePK,omitempty"`
	MainOrderTypeName           string               `json:"mainOrderTypeName,omitempty"`
	OrderDate                   time.Time            `json:"orderDate,omitempty"`
	CurrencyRatesFK             int32                `json:"currencyRatesFK,omitempty"`
	CurrencyCode                string               `json:"currencyCode,omitempty"`
	CurrencySymbol              string               `json:"currencySymbol,omitempty"`
	CurrencyRate                float64              `json:"currencyRate,omitempty"`
	MainCreditCardsFK           int32                `json:"mainCreditCardsFK,omitempty"`
	TaxExempt                   bool                 `json:"taxExempt,omitempty"`
	PriceWon                    float64              `json:"priceWon,omitempty"`
	ConvSubTotal                float64              `json:"convSubTotal,omitempty"`
	ConvVAT                     float64              `json:"convVAT,omitempty"`
	PriceKRVAT                  float64              `json:"priceKRVAT,omitempty"`
	ProductVAT                  float64              `json:"productVAT,omitempty"`
	Country                     string               `json:"country,omitempty"`
	ProductShipPrice            float64              `json:"productShipPrice,omitempty"`
	IsShippable                 bool                 `json:"isShippable,omitempty"`
	IsInternetSpecial           bool                 `json:"isInternetSpecial,omitempty"`
	ImportOrder                 bool                 `json:"importOrder,omitempty"`
	ShippingMainFK              int32                `json:"shippingMainFK,omitempty"`
	KrGuaranteeNo               string               `json:"krGuaranteeNo,omitempty"`
	ConvTotal                   float64              `json:"convTotal,omitempty"`
	MFName                      string               `json:"mFName,omitempty"`
	MLName                      string               `json:"mLName,omitempty"`
	AllowAdminProcessing        bool                 `json:"allowAdminProcessing,omitempty"`
	ReqdFedExSignature          string               `json:"reqdFedExSignature,omitempty"`
	ShippingPackageCode         string               `json:"shippingPackageCode,omitempty"`
	ShippingConfirmationType    string               `json:"shippingConfirmationType,omitempty"`
	OrderProcessingFees         float64              `json:"orderProcessingFees,omitempty"`
	NoOfInstallments            int32                `json:"noOfInstallments,omitempty"`
	RelatedMainOrders           string               `json:"relatedMainOrders,omitempty"`
	CartKey                     string               `json:"cartKey,omitempty"`
	OrderItems                  []OrderInfoItemModel `json:"orderItems,omitempty"`
	OrderTaxTotals              *OrderTaxTotalsModel `json:"orderTaxTotals,omitempty"`
	ShippingZone                int32                `json:"shippingZone,omitempty"`
}
