/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type SmartDeliveryViewModel struct {
	Active                    bool      `json:"active"`
	IsPaymentSetup            bool      `json:"isPaymentSetup"`
	AgreedToTerms             bool      `json:"agreedToTerms"`
	IsPickupOffered           bool      `json:"isPickupOffered"`
	IsPickup                  bool      `json:"isPickup"`
	AskForKidsDonation        bool      `json:"askForKidsDonation"`
	NextDeliveryDate          time.Time `json:"nextDeliveryDate,omitempty"`
	StartedDate               time.Time `json:"startedDate,omitempty"`
	ItemsTotal                string    `json:"itemsTotal,omitempty"`
	ShipMethod                int32     `json:"shipMethod,omitempty"`
	ShippingInstructions      string    `json:"shippingInstructions,omitempty"`
	SignatureRequired         bool      `json:"signatureRequired,omitempty"`
	NoPersonalUseOnly         bool      `json:"noPersonalUseOnly,omitempty"`
	AskForPersonalUse         bool      `json:"askForPersonalUse,omitempty"`
	AskForWalletUse           bool      `json:"askForWalletUse,omitempty"`
	WalletFirst               bool      `json:"walletFirst,omitempty"`
	PartialWallet             bool      `json:"partialWallet,omitempty"`
	IsValidPhotoID            bool      `json:"isValidPhotoID,omitempty"`
	IsImportOrder             bool      `json:"isImportOrder,omitempty"`
	IsImportAllowed           bool      `json:"isImportAllowed,omitempty"`
	PaymentType               string    `json:"paymentType,omitempty"`
	ManualPayment             bool      `json:"manualPayment,omitempty"`
	ShowAbandonedOrderWarning bool      `json:"showAbandonedOrderWarning,omitempty"`
	MinCV                     int32     `json:"minCV,omitempty"`
	AlreadyPaidThisMonth      bool      `json:"alreadyPaidThisMonth,omitempty"`
}
