/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type ShippingMethodsViewModel struct {
	Message        string                    `json:"message,omitempty"`
	ZipCodeMessage string                    `json:"zipCodeMessage,omitempty"`
	ShowShipFilter bool                      `json:"showShipFilter,omitempty"`
	Methods        []ShippingMethodViewModel `json:"methods,omitempty"`
}
