/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type RmaProducts struct {
	Id                   int32   `json:"id,omitempty"`
	ProductFK            int32   `json:"productFK,omitempty"`
	MainOrderFK          int32   `json:"mainOrderFK,omitempty"`
	RmANumber            int32   `json:"rmA_Number,omitempty"`
	ProratedProductPrice float64 `json:"proratedProductPrice,omitempty"`
	ProductName          string  `json:"productName,omitempty"`
	OrderQty             int32   `json:"orderQty,omitempty"`
	ToBeReturnedQty      int32   `json:"toBeReturnedQty,omitempty"`
}
