/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type RewardPointsCustomerTransactionModel struct {
	EffectiveDate       time.Time `json:"effectiveDate,omitempty"`
	Description         string    `json:"description,omitempty"`
	MainOrdersFK        int32     `json:"mainOrdersFK,omitempty"`
	OrderTotal          float64   `json:"orderTotal,omitempty"`
	ConvTotal           float64   `json:"convTotal,omitempty"`
	CurrencySymbol      string    `json:"currencySymbol,omitempty"`
	TransactionAmount   float64   `json:"transactionAmount,omitempty"`
	RewardPointsBalance float64   `json:"rewardPointsBalance,omitempty"`
	ExpirationDate      time.Time `json:"expirationDate,omitempty"`
	RunningTotal        int32     `json:"runningTotal,omitempty"`
	CustomerRank        string    `json:"customerRank,omitempty"`
}
