/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type MainOrderModel struct {
	RefSiteURL                    string                   `json:"refSiteURL,omitempty"`
	ConvShipTotalFormat           string                   `json:"convShipTotalFormat,omitempty"`
	ConvTaxesFormat               string                   `json:"convTaxesFormat,omitempty"`
	ConvProductTaxFormat          string                   `json:"convProductTaxFormat,omitempty"`
	ConvShippingTaxFormat         string                   `json:"convShippingTaxFormat,omitempty"`
	ConvTotalProductTaxFormat     string                   `json:"convTotalProductTaxFormat,omitempty"`
	ConvAdditionalTaxFormat       string                   `json:"convAdditionalTaxFormat,omitempty"`
	ConvSubtotalFormat            string                   `json:"convSubtotalFormat,omitempty"`
	ConvOrderProcessingFeesFormat string                   `json:"convOrderProcessingFeesFormat,omitempty"`
	ConvRefundFormat              string                   `json:"convRefundFormat,omitempty"`
	ConvDiscountFormat            string                   `json:"convDiscountFormat,omitempty"`
	CurrencyRate                  float64                  `json:"currencyRate,omitempty"`
	IsCCAP                        bool                     `json:"isCCAP"`
	PaidStatusFK                  int32                    `json:"paidStatusFK,omitempty"`
	MarkedPaidDate                time.Time                `json:"markedPaidDate,omitempty"`
	MainOrderTypeFK               int32                    `json:"mainOrderTypeFK"`
	MainTypeFK                    int32                    `json:"mainTypeFK"`
	PaymentMethod                 string                   `json:"paymentMethod"`
	Splitorders                   []Splitorders            `json:"splitorders,omitempty"`
	IsPB                          bool                     `json:"isPB,omitempty"`
	IsPA                          bool                     `json:"isPA,omitempty"`
	IsCC                          bool                     `json:"isCC,omitempty"`
	OrderTypeValue                string                   `json:"orderTypeValue,omitempty"`
	ShowOrderInvoice              bool                     `json:"showOrderInvoice,omitempty"`
	ShowShipmentInvoice           bool                     `json:"showShipmentInvoice,omitempty"`
	Cv                            int32                    `json:"cv,omitempty"`
	PersonalOrdersBP              float64                  `json:"personalOrdersBP,omitempty"`
	PersonalOrdersSP              float64                  `json:"personalOrdersSP,omitempty"`
	Email                         string                   `json:"email,omitempty"`
	Products                      []OrdersShipmentProduct  `json:"products,omitempty"`
	OrderDate                     time.Time                `json:"orderDate"`
	MainOrdersPK                  int32                    `json:"mainOrdersPK"`
	OrderType                     string                   `json:"orderType"`
	FinalOrderType                string                   `json:"finalOrderType,omitempty"`
	SiteURL                       string                   `json:"siteURL"`
	EncOrderNumber                string                   `json:"encOrderNumber,omitempty"`
	CurrencySymbol                string                   `json:"currencySymbol"`
	CurrencyCode                  string                   `json:"currencyCode,omitempty"`
	PaidStatus                    bool                     `json:"paidStatus"`
	HasTaxInvoice                 bool                     `json:"hasTaxInvoice"`
	HasCommercialInvoice          bool                     `json:"hasCommercialInvoice"`
	HasCreditNote                 bool                     `json:"hasCreditNote"`
	IsShippingPending             bool                     `json:"isShippingPending,omitempty"`
	MainFK                        int32                    `json:"mainFK,omitempty"`
	VoucherURL                    string                   `json:"voucherURL,omitempty"`
	ShipCountry                   string                   `json:"shipCountry,omitempty"`
	ShippingStatus                string                   `json:"shippingStatus,omitempty"`
	OrderShippingStatus           string                   `json:"orderShippingStatus,omitempty"`
	PaidStatusValue               string                   `json:"paidStatusValue,omitempty"`
	Quantity                      int32                    `json:"quantity,omitempty"`
	Phone                         string                   `json:"phone,omitempty"`
	ShipFirstName                 string                   `json:"shipFirstName,omitempty"`
	ShipLastName                  string                   `json:"shipLastName,omitempty"`
	Total                         float64                  `json:"total,omitempty"`
	ConvTotal                     float64                  `json:"convTotal,omitempty"`
	ConvTotalFormat               string                   `json:"convTotalFormat,omitempty"`
	SubTotal                      float64                  `json:"subTotal,omitempty"`
	ConvSubtotal                  float64                  `json:"convSubtotal,omitempty"`
	ShipTotal                     float64                  `json:"shipTotal,omitempty"`
	ConvShipTotal                 float64                  `json:"convShipTotal,omitempty"`
	Taxes                         float64                  `json:"taxes,omitempty"`
	TaxLabel                      string                   `json:"taxLabel,omitempty"`
	ProductTax                    float64                  `json:"productTax,omitempty"`
	ShippingTax                   float64                  `json:"shippingTax,omitempty"`
	TotalProductTax               float64                  `json:"totalProductTax,omitempty"`
	AdditionalTaxLabel            string                   `json:"additionalTaxLabel,omitempty"`
	AdditionalTax                 float64                  `json:"additionalTax,omitempty"`
	ConvTaxes                     float64                  `json:"convTaxes,omitempty"`
	OrderProcessingFees           float64                  `json:"orderProcessingFees,omitempty"`
	ConvOrderProcessingFees       float64                  `json:"convOrderProcessingFees,omitempty"`
	Discount                      float64                  `json:"discount,omitempty"`
	ConvDiscount                  float64                  `json:"convDiscount,omitempty"`
	RefundAmount                  float64                  `json:"refundAmount,omitempty"`
	ConvRefund                    float64                  `json:"convRefund,omitempty"`
	SalesCampaignFK               int32                    `json:"salesCampaignFK,omitempty"`
	Paidstatusfk                  int32                    `json:"paidstatusfk,omitempty"`
	DeliveryDate                  time.Time                `json:"deliveryDate,omitempty"`
	ShippingDetails               []MainOrderTrackingModel `json:"shippingDetails,omitempty"`
	OrderItems                    []MainOrderItemModel     `json:"orderItems,omitempty"`
	Payments                      []OrderPayments          `json:"payments,omitempty"`
	IsPrepaidOrder                bool                     `json:"isPrepaidOrder,omitempty"`
	ShowInvoice                   bool                     `json:"showInvoice,omitempty"`
	KrGuaranteeNo                 string                   `json:"krGuaranteeNo,omitempty"`
	WeChatOrderNumber             string                   `json:"weChatOrderNumber,omitempty"`
	MemberID                      string                   `json:"memberID,omitempty"`
}
