/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type RewardPointsCustomerStatusViewModel struct {
	CustomerRank      string    `json:"customerRank,omitempty"`
	CustomerRankLevel int32     `json:"customerRankLevel,omitempty"`
	WindowSD          time.Time `json:"windowSD,omitempty"`
	WindowED          time.Time `json:"windowED,omitempty"`
}
