/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type CartAddressFormModel struct {
	FirstName     string `json:"firstName"`
	LastName      string `json:"lastName"`
	Company       string `json:"company,omitempty"`
	Address1      string `json:"address1"`
	Address2      string `json:"address2,omitempty"`
	Address3      string `json:"address3,omitempty"`
	City          string `json:"city"`
	State         string `json:"state"`
	PostalCode    string `json:"postalCode,omitempty"`
	Country       string `json:"country"`
	IsPOBox       bool   `json:"isPOBox,omitempty"`
	IsResidential bool   `json:"isResidential,omitempty"`
}
