/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type CustomerReferralReturnModel struct {
	ReferralStatus    string `json:"referralStatus,omitempty"`
	ReferralStatusKey string `json:"referralStatusKey,omitempty"`
	ReferralID        string `json:"referralID,omitempty"`
	SponsorMainFK     int32  `json:"sponsorMainFK,omitempty"`
	ReferralSuccess   bool   `json:"referralSuccess,omitempty"`
	ReferralFirstName string `json:"referralFirstName,omitempty"`
	ReferralLastName  string `json:"referralLastName,omitempty"`
	ReferralEmail     string `json:"referralEmail,omitempty"`
}
