/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type OrderComplete3Ds2Model struct {
	MainOrderPk       int32                             `json:"mainOrderPk"`
	PaymentMethodCode string                            `json:"paymentMethodCode,omitempty"`
	Params3DS         []OrderComplete3Ds2ModelParameter `json:"params3DS,omitempty"`
	Source            string                            `json:"source,omitempty"`
}
