/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type RmasSearchQueryParams struct {
	RmaNumber       int32     `json:"rmaNumber,omitempty"`
	OrderNumber     int32     `json:"orderNumber,omitempty"`
	CustomerSiteurl string    `json:"customerSiteurl,omitempty"`
	CustomerName    string    `json:"customerName,omitempty"`
	IssuedBy        string    `json:"issuedBy,omitempty"`
	IssuedDate      time.Time `json:"issuedDate,omitempty"`
	JnsDepartment   string    `json:"jnsDepartment,omitempty"`
	StatusId        string    `json:"statusId,omitempty"`
	RecivedDate     time.Time `json:"recivedDate,omitempty"`
	RefundDate      time.Time `json:"refundDate,omitempty"`
	Offset          int32     `json:"offset,omitempty"`
	Limit           int32     `json:"limit,omitempty"`
	OrderBy         string    `json:"orderBy,omitempty"`
}
