/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type BagQueryModel struct {
	BagPK       int32  `json:"bagPK,omitempty"`
	CustomerPK  int32  `json:"customerPK,omitempty"`
	CartType    string `json:"cartType,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	Culture     string `json:"culture,omitempty"`
	SiteUrl     string `json:"siteUrl,omitempty"`
}
