/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

type CartSetShippingFormModel struct {
	ShippingChartTypeFk int32   `json:"shippingChartTypeFk,omitempty"`
	ShippingCost        float64 `json:"shippingCost,omitempty"`
	SignatureFee        float64 `json:"signatureFee,omitempty"`
	SignatureRequested  bool    `json:"signatureRequested,omitempty"`
	SignatureRequired   bool    `json:"signatureRequired,omitempty"`
}
