/*
 * Cart-Api v1
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cart_v1

import (
	"time"
)

type SmartDeliveryFormModel struct {
	IsPickup          bool      `json:"isPickup,omitempty"`
	ShipMethod        int32     `json:"shipMethod,omitempty"`
	SignatureReq      bool      `json:"signatureReq,omitempty"`
	NoPersonalUseOnly bool      `json:"noPersonalUseOnly,omitempty"`
	WalletFirst       bool      `json:"walletFirst,omitempty"`
	PartialWallet     bool      `json:"partialWallet,omitempty"`
	PaymentType       string    `json:"paymentType,omitempty"`
	NextRunDate       time.Time `json:"nextRunDate,omitempty"`
}
