/*
 * Security-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package security

type SmartMobileValidateTokenRequest struct {
	JwtToken          string `json:"jwtToken,omitempty"`
	JofficeToken      string `json:"jofficeToken,omitempty"`
	DeviceCultureName string `json:"deviceCultureName,omitempty"`
}
