/*
 * Security-Api v2
 *
 * A Microsoft WebApi2 application. For use by Jeunesse and its Partners, this api has a focus on product and order creation
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package security

type WalletTokenRequestModel struct {
	QuestionPk             int32  `json:"questionPk,omitempty"`
	Answer                 string `json:"answer,omitempty"`
	CaptchaId              string `json:"captchaId,omitempty"`
	UserEnteredCaptchaCode string `json:"userEnteredCaptchaCode,omitempty"`
	UserName               string `json:"userName"`
	Password               string `json:"password,omitempty"`
	SignupKey              string `json:"signupKey,omitempty"`
}
